### ISSUE TITLE
Icon request: Elixir files

### ISSUE THREAD

**Issue by ejpcmac** [file-icons/source#22] opened 2017-05-17 08:11 UTC
Hi,

Could you add [Elixir](http://elixir-lang.org/) icons? There are mainly three file types:

* elixir source files `.ex`,
* elixir script files `.exs`,
* embedded Elixir `.eex`
    * elixir HTML templates `.html.eex`
    * elixir JSON templates `.json.eex`
    * elixir text templates `.text.eex` (I think the bare `.eex` icon fits perfectly here)

**Comment by Alhadis** [comment] 2017-05-17 08:15
What's wrong with the icon we're [currently using](https://github.com/file-icons/MFixx/blob/master/charmap.md#F113)...?

<img src="https://cloud.githubusercontent.com/assets/2346707/26144556/a9bda2b4-3b2c-11e7-9691-a536a38ecb02.png" width="315" alt="Figure 1" />

**Comment by Alhadis** [comment] 2017-05-17 09:06
@ejpcmac I'm going to close this, because there's no point in adding a duplicate icon. Please consult the character-maps of the package's [bundled icon-fonts](https://github.com/file-icons/atom#icon-reference) to see what other icons are available.

**Closed by Alhadis** 2017-05-17 09:06 UTC

**Comment by ejpcmac** [comment] 2017-05-17 09:13
@Alhadis Oh, I’m very sorry. I just discovered this package at work (where I don’t do Elixir) and I quick searched in [this file](https://github.com/file-icons/source/blob/master/charmap.md) where it was not present, but didn’t checked by simply creating a `.ex` file… :man_facepalming: Very sorry again for wasting your time.

**Comment by Alhadis** [comment] 2017-05-17 09:17
> creating a .ex file… 🤦‍♂️ Very sorry

I swear the older I get, the less I understand emoji...

<img src="https://cloud.githubusercontent.com/assets/2346707/26146964/53f699d6-3b35-11e7-947f-52b5f9c20a44.png" width="411" alt="Figure 2" />

**Comment by ejpcmac** [comment] 2017-05-17 09:19
@Alhadis The first one is a man facepalming, and this is very strange because I don’t see the second one on my computer. It is not intended to be there…

**Comment by Alhadis** [comment] 2017-05-17 09:21
Yup, confirmed: I'm too old for this shit. 😿  Don't get me started on cats with human faces, either.
